import 'dart:io';

/// Writes [repo]/ios/Flutter/Secrets.xcconfig from [repo]/.env (GOOGLE_API_KEY=...).
/// Run from repo root: `dart run tool/sync_google_api_key_to_ios.dart`
void main() {
  final repo = Directory.current;
  final envFile = File('${repo.path}${Platform.pathSeparator}.env');
  final outFile = File(
    '${repo.path}${Platform.pathSeparator}ios${Platform.pathSeparator}Flutter${Platform.pathSeparator}Secrets.xcconfig',
  );

  var key = '';
  if (envFile.existsSync()) {
    for (final line in envFile.readAsLinesSync()) {
      final t = line.trim();
      if (t.isEmpty || t.startsWith('#')) continue;
      if (t.startsWith('GOOGLE_API_KEY=')) {
        key = t.substring('GOOGLE_API_KEY='.length).trim();
        if ((key.startsWith('"') && key.endsWith('"')) ||
            (key.startsWith("'") && key.endsWith("'"))) {
          key = key.substring(1, key.length - 1);
        }
        break;
      }
    }
  }

  outFile.parent.createSync(recursive: true);
  outFile.writeAsStringSync(
    '// Generated by tool/sync_google_api_key_to_ios.dart — do not commit real keys if repo is public.\n'
    'GOOGLE_API_KEY=$key\n',
  );
  stdout.writeln('Wrote ${outFile.path}');
}
